version: '3.8'

services:
  oxidized:
    restart: always
    image: oxidized/oxidized:latest
    ports:
      - "8888:8888/tcp"
    environment:
      CONFIG_RELOAD_INTERVAL: 600
    volumes:
      - /etc/oxidized:/root/.config/oxidized
